// Copyright 2026 Fynd (Shopsense Retail Technologies Limited)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package server

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"regexp"
	"runtime/debug"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gofynd/fit-go/errors"
)

// Middleware is the standard middleware signature used throughout fit.go.
// With gin, this is gin.HandlerFunc.
type Middleware = gin.HandlerFunc

// WrapHTTPMiddleware converts a standard http middleware into a gin.HandlerFunc.
func WrapHTTPMiddleware(mw func(http.Handler) http.Handler) gin.HandlerFunc {
	return func(c *gin.Context) {
		mw(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			c.Request = r
			c.Next()
		})).ServeHTTP(c.Writer, c.Request)
	}
}

// contextKey is an unexported type for context keys defined in this package.
type contextKey int

const (
	ctxKeyApplicationData contextKey = iota
	ctxKeyUserData
	ctxKeyDecodedToken
	ctxKeyRequestID
)

// Gin context key strings for c.Set/c.Get.
const (
	ginKeyApplicationData = "fit.applicationData"
	ginKeyUserData        = "fit.userData"
	ginKeyDecodedToken    = "fit.decodedToken"
	ginKeyRequestID       = "fit.requestID"
)

// ---------------------------------------------------------------------------
// Context helpers (work with both gin context and standard context)
// ---------------------------------------------------------------------------

// ApplicationDataFromContext returns the parsed x-application-data header value
// that was attached by the ParseApplicationData middleware.
func ApplicationDataFromContext(ctx context.Context) map[string]interface{} {
	// Try gin context first
	if gc, ok := ctx.(*gin.Context); ok {
		if v, exists := gc.Get(ginKeyApplicationData); exists {
			if m, ok := v.(map[string]interface{}); ok {
				return m
			}
		}
	}
	v, _ := ctx.Value(ctxKeyApplicationData).(map[string]interface{})
	return v
}

// UserDataFromContext returns the parsed x-user-data header value
// that was attached by the ParseUserData middleware.
func UserDataFromContext(ctx context.Context) map[string]interface{} {
	if gc, ok := ctx.(*gin.Context); ok {
		if v, exists := gc.Get(ginKeyUserData); exists {
			if m, ok := v.(map[string]interface{}); ok {
				return m
			}
		}
	}
	v, _ := ctx.Value(ctxKeyUserData).(map[string]interface{})
	return v
}

// DecodedTokenFromContext returns the decoded JWT claims that were
// attached by the AuthorizeJWTToken middleware.
func DecodedTokenFromContext(ctx context.Context) map[string]interface{} {
	if gc, ok := ctx.(*gin.Context); ok {
		if v, exists := gc.Get(ginKeyDecodedToken); exists {
			if m, ok := v.(map[string]interface{}); ok {
				return m
			}
		}
	}
	v, _ := ctx.Value(ctxKeyDecodedToken).(map[string]interface{})
	return v
}

// RequestIDFromContext returns the request ID generated by the RequestID middleware.
func RequestIDFromContext(ctx context.Context) string {
	if gc, ok := ctx.(*gin.Context); ok {
		if v, exists := gc.Get(ginKeyRequestID); exists {
			if s, ok := v.(string); ok {
				return s
			}
		}
	}
	v, _ := ctx.Value(ctxKeyRequestID).(string)
	return v
}

// ---------------------------------------------------------------------------
// Route path normalization (for logging / Prometheus labels)
// ---------------------------------------------------------------------------

var (
	uuidPattern    = regexp.MustCompile(`/[a-fA-F0-9-]{36}`)
	numericPattern = regexp.MustCompile(`/\d+`)
)

// normalizeRoutePath replaces UUIDs with :uuid and numeric segments with :id.
// UUIDs are matched first to avoid partial replacement by the numeric pattern.
func normalizeRoutePath(path string) string {
	path = uuidPattern.ReplaceAllString(path, "/:uuid")
	path = numericPattern.ReplaceAllString(path, "/:id")
	return path
}

// ---------------------------------------------------------------------------
// responseRecorder captures status code and body for logging.
// (kept for backward compatibility with non-gin code paths)
// ---------------------------------------------------------------------------

type responseRecorder struct {
	http.ResponseWriter
	statusCode int
	written    bool
}

func newResponseRecorder(w http.ResponseWriter) *responseRecorder {
	return &responseRecorder{ResponseWriter: w, statusCode: http.StatusOK}
}

func (r *responseRecorder) WriteHeader(code int) {
	if !r.written {
		r.statusCode = code
		r.written = true
	}
	r.ResponseWriter.WriteHeader(code)
}

func (r *responseRecorder) Write(b []byte) (int, error) {
	if !r.written {
		r.statusCode = http.StatusOK
		r.written = true
	}
	return r.ResponseWriter.Write(b)
}

// Unwrap provides access to the underlying ResponseWriter for http.Flusher etc.
func (r *responseRecorder) Unwrap() http.ResponseWriter {
	return r.ResponseWriter
}

// ---------------------------------------------------------------------------
// LogRequestResponse middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// LogRequestResponseConfig controls the behaviour of the log middleware.
type LogRequestResponseConfig struct {
	// Logger is the structured logger to use. If nil, slog.Default() is used.
	Logger *slog.Logger
	// IncludeHeaders is a comma-separated list of header names to include in logs.
	// Mirrors the INCLUDE_HEADERS_IN_LOG env var.
	IncludeHeaders string
	// MetricsRecorder is an optional callback invoked with method, route, status, and
	// duration so that the caller can record Prometheus histograms.
	MetricsRecorder func(method, route, status string, durationMs float64)
}

// LogRequestResponse returns a gin middleware that logs incoming requests and outgoing
// responses. Health-check paths (/_healthz, /_readyz) are skipped.
func LogRequestResponse(cfg LogRequestResponseConfig) gin.HandlerFunc {
	l := cfg.Logger
	if l == nil {
		l = slog.Default()
	}

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip health/readiness probes
		if strings.Contains(path, "/_healthz") || strings.Contains(path, "/_readyz") {
			c.Next()
			return
		}

		start := time.Now()

		// Collect optional headers
		attrs := []slog.Attr{
			slog.String("request_url", c.Request.URL.RequestURI()),
			slog.String("request_method", c.Request.Method),
			slog.String("step", "REQ"),
		}
		if cfg.IncludeHeaders != "" {
			for _, h := range strings.Split(cfg.IncludeHeaders, ",") {
				h = strings.TrimSpace(h)
				if h != "" {
					attrs = append(attrs, slog.String(h, c.Request.Header.Get(h)))
				}
			}
		}
		l.LogAttrs(c.Request.Context(), slog.LevelInfo,
			fmt.Sprintf("[REQ] Incoming %s request for %s", c.Request.Method, path),
			attrs...,
		)

		c.Next()

		duration := time.Since(start)
		statusCode := c.Writer.Status()

		// Record Prometheus metrics via callback
		if cfg.MetricsRecorder != nil {
			route := normalizeRoutePath(path)
			cfg.MetricsRecorder(c.Request.Method, route, strconv.Itoa(statusCode), float64(duration.Milliseconds()))
		}

		// Log response
		level := slog.LevelInfo
		if statusCode >= 500 {
			level = slog.LevelError
		} else if statusCode >= 400 {
			level = slog.LevelWarn
		}

		l.LogAttrs(c.Request.Context(), level,
			fmt.Sprintf("[RES] Outgoing %s response from %s", c.Request.Method, path),
			slog.String("request_url", c.Request.URL.RequestURI()),
			slog.String("request_method", c.Request.Method),
			slog.String("step", "RES"),
			slog.Int("response_status", statusCode),
			slog.Duration("duration", duration),
		)
	}
}

// GinLogRequestResponse is an alias for LogRequestResponse for use in server.go.
var GinLogRequestResponse = LogRequestResponse

// ---------------------------------------------------------------------------
// ParseApplicationData middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// GinParseApplicationData is a gin middleware that parses the x-application-data
// header (JSON) and stores the result in the gin context.
// Retrieve it with ApplicationDataFromContext.
func GinParseApplicationData(c *gin.Context) {
	header := c.GetHeader("x-application-data")
	if header != "" {
		data, err := parseHeaderJSON(header)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusUnauthorized, map[string]interface{}{
				"error": map[string]interface{}{
					"code":    "APPLICATION_HEADER_JSON_PARSE_FAILURE",
					"message": "failed to parse x-application-data header",
					"meta": map[string]interface{}{
						"rawApplicationHeader": header,
					},
				},
			})
			return
		}
		c.Set(ginKeyApplicationData, data)
		ctx := context.WithValue(c.Request.Context(), ctxKeyApplicationData, data)
		c.Request = c.Request.WithContext(ctx)
	}
	c.Next()
}

// ---------------------------------------------------------------------------
// ParseUserData middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// GinParseUserData is a gin middleware that parses the x-user-data header (JSON)
// and stores the result in the gin context. Retrieve it with UserDataFromContext.
func GinParseUserData(c *gin.Context) {
	header := c.GetHeader("x-user-data")
	if header != "" {
		data, err := parseHeaderJSON(header)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusUnauthorized, map[string]interface{}{
				"error": map[string]interface{}{
					"code":    "USER_HEADER_JSON_PARSE_FAILURE",
					"message": "failed to parse x-user-data header",
					"meta": map[string]interface{}{
						"rawUserHeader": header,
					},
				},
			})
			return
		}
		c.Set(ginKeyUserData, data)
		ctx := context.WithValue(c.Request.Context(), ctxKeyUserData, data)
		c.Request = c.Request.WithContext(ctx)
	}
	c.Next()
}

// parseHeaderJSON parses a header value that can be either a single JSON object
// string or a JSON array of strings (where the first element is the JSON object).
// This matches the behavior where headers can arrive in either format.
func parseHeaderJSON(header string) (map[string]interface{}, error) {
	header = strings.TrimSpace(header)

	// Try parsing as a single JSON object first.
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(header), &data); err == nil {
		return data, nil
	}

	// Try parsing as a JSON array of strings.
	var arr []string
	if err := json.Unmarshal([]byte(header), &arr); err == nil && len(arr) > 0 {
		if err := json.Unmarshal([]byte(arr[0]), &data); err == nil {
			return data, nil
		}
	}

	return nil, fmt.Errorf("failed to parse header JSON: %s", header)
}

// ---------------------------------------------------------------------------
// ErrorHandler middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// ErrorHandler is a gin middleware that catches panics and returns structured JSON
// error responses. If the recovered value is a *errors.FitError, its HTTP status
// and structured body are used. Otherwise a 400 Bad Request is returned.
func ErrorHandler(logger *slog.Logger) gin.HandlerFunc {
	if logger == nil {
		logger = slog.Default()
	}
	return func(c *gin.Context) {
		defer func() {
			if rv := recover(); rv != nil {
				logger.Error("panic recovered in ErrorHandler",
					"error", rv,
					"stack", string(debug.Stack()),
					"path", c.Request.URL.Path,
				)

				switch e := rv.(type) {
				case *errors.FitError:
					status := e.HTTPStatusCode
					if status < 200 || status > 599 {
						status = http.StatusInternalServerError
					}
					c.AbortWithStatusJSON(status, map[string]interface{}{
						"error": map[string]interface{}{
							"code":    e.Code,
							"message": e.GetMessage(),
							"meta":    e.Meta,
						},
					})
				case error:
					c.AbortWithStatusJSON(http.StatusBadRequest, map[string]interface{}{
						"error": map[string]interface{}{
							"message": e.Error(),
						},
					})
				default:
					c.AbortWithStatusJSON(http.StatusInternalServerError, map[string]interface{}{
						"error": map[string]interface{}{
							"message": fmt.Sprintf("%v", rv),
						},
					})
				}
			}
		}()

		c.Next()
	}
}

// ---------------------------------------------------------------------------
// Recovery middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// Recovery is a panic-recovery gin middleware that logs the panic and returns 500.
func Recovery(logger *slog.Logger) gin.HandlerFunc {
	if logger == nil {
		logger = slog.Default()
	}
	return func(c *gin.Context) {
		defer func() {
			if rv := recover(); rv != nil {
				logger.Error("panic recovered",
					"error", rv,
					"stack", string(debug.Stack()),
					"path", c.Request.URL.Path,
				)
				if !c.Writer.Written() {
					c.AbortWithStatusJSON(http.StatusInternalServerError, map[string]interface{}{
						"error": map[string]interface{}{
							"message": "internal server error",
						},
					})
				}
			}
		}()
		c.Next()
	}
}

// ---------------------------------------------------------------------------
// AuthorizeJWTToken middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// JWTOptions configures the JWT authorisation middleware.
type JWTOptions struct {
	// Secret is the HMAC-SHA256 secret. If empty, the JWT_SECRET_DELETE_ENTITY
	// env var is used (.
	Secret string
	// ExpectedPayload is a map of claims that must match the decoded token
	// (excluding standard claims like iat, exp, nbf, aud, sub, iss).
	// If nil, the middleware attempts to match company_id from URL params.
	ExpectedPayload map[string]interface{}
}

// standardClaims are JWT registered claim names excluded from payload comparison.
var standardClaims = map[string]struct{}{
	"iat": {}, "exp": {}, "nbf": {}, "aud": {}, "sub": {}, "iss": {},
}

// AuthorizeJWTToken returns a gin middleware that validates a Bearer JWT token
// using HS256 and optionally checks that the decoded payload matches the
// expected values. Decoded claims are stored in context - retrieve with
// DecodedTokenFromContext.
func AuthorizeJWTToken(opts JWTOptions) gin.HandlerFunc {
	return func(c *gin.Context) {
		secret := opts.Secret
		if secret == "" {
			secret = envGet("JWT_SECRET_DELETE_ENTITY", "")
		}

		// Extract Bearer token
		authHeader := c.GetHeader("Authorization")
		token := strings.TrimPrefix(authHeader, "Bearer ")
		token = strings.TrimSpace(token)
		if token == "" || token == authHeader {
			c.AbortWithStatusJSON(http.StatusUnauthorized, map[string]string{"message": "Unauthorized"})
			return
		}

		// Decode and verify HS256
		claims, err := verifyHS256(token, secret)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusUnauthorized, map[string]string{"message": "Unauthorized"})
			return
		}

		// Store decoded token in gin context and standard context
		c.Set(ginKeyDecodedToken, claims)
		ctx := context.WithValue(c.Request.Context(), ctxKeyDecodedToken, claims)
		c.Request = c.Request.WithContext(ctx)

		// Build expected payload
		expected := opts.ExpectedPayload
		if expected == nil {
			companyID := c.Param("company_id")
			if companyID != "" {
				expected = map[string]interface{}{"company_id": companyID}
			}
		}

		// Compare non-standard claims if expected is set
		if expected != nil {
			actual := make(map[string]interface{})
			for k, v := range claims {
				if _, skip := standardClaims[k]; !skip {
					actual[k] = v
				}
			}
			if !jsonEqual(expected, actual) {
				c.AbortWithStatusJSON(http.StatusUnauthorized, map[string]string{"message": "Unauthorized"})
				return
			}
		}

		c.Next()
	}
}

// ---------------------------------------------------------------------------
// JWT HS256 verification (no external dependencies)
// ---------------------------------------------------------------------------

// verifyHS256 decodes a JWT token signed with HMAC-SHA256 and returns the
// claims payload. It validates the signature and checks exp/nbf if present.
func verifyHS256(tokenStr, secret string) (map[string]interface{}, error) {
	parts := strings.Split(tokenStr, ".")
	if len(parts) != 3 {
		return nil, fmt.Errorf("jwt: invalid token format")
	}

	// Decode header
	headerBytes, err := base64URLDecode(parts[0])
	if err != nil {
		return nil, fmt.Errorf("jwt: invalid header encoding: %w", err)
	}
	var header map[string]interface{}
	if err := json.Unmarshal(headerBytes, &header); err != nil {
		return nil, fmt.Errorf("jwt: invalid header JSON: %w", err)
	}
	if alg, _ := header["alg"].(string); alg != "HS256" {
		return nil, fmt.Errorf("jwt: unsupported algorithm %q", alg)
	}

	// Verify signature
	signingInput := parts[0] + "." + parts[1]
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(signingInput))
	expectedSig := mac.Sum(nil)
	actualSig, err := base64URLDecode(parts[2])
	if err != nil {
		return nil, fmt.Errorf("jwt: invalid signature encoding: %w", err)
	}
	if !hmac.Equal(expectedSig, actualSig) {
		return nil, fmt.Errorf("jwt: signature verification failed")
	}

	// Decode payload
	payloadBytes, err := base64URLDecode(parts[1])
	if err != nil {
		return nil, fmt.Errorf("jwt: invalid payload encoding: %w", err)
	}
	var claims map[string]interface{}
	if err := json.Unmarshal(payloadBytes, &claims); err != nil {
		return nil, fmt.Errorf("jwt: invalid payload JSON: %w", err)
	}

	// Check exp
	now := float64(time.Now().Unix())
	if exp, ok := claims["exp"].(float64); ok && now > exp {
		return nil, fmt.Errorf("jwt: token expired")
	}
	// Check nbf
	if nbf, ok := claims["nbf"].(float64); ok && now < nbf {
		return nil, fmt.Errorf("jwt: token not yet valid")
	}

	return claims, nil
}

// base64URLDecode decodes a base64url-encoded string (with or without padding).
func base64URLDecode(s string) ([]byte, error) {
	// Add padding if necessary
	switch len(s) % 4 {
	case 2:
		s += "=="
	case 3:
		s += "="
	}
	return base64.URLEncoding.DecodeString(s)
}

// jsonEqual compares two maps by marshalling to JSON. This mirrors the lodash
// isEqual comparison used in the JS implementation.
func jsonEqual(a, b map[string]interface{}) bool {
	aj, err1 := json.Marshal(a)
	bj, err2 := json.Marshal(b)
	if err1 != nil || err2 != nil {
		return false
	}
	return string(aj) == string(bj)
}

// ---------------------------------------------------------------------------
// DecryptionMiddleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// DecryptFunc is the function signature for decrypting a string value.
// The caller should provide their encryption.Decrypt implementation.
type DecryptFunc func(ciphertext string) (string, error)

// DecryptionMiddleware returns a gin middleware that decrypts specified fields in
// the JSON response body. locations are dot-notation paths (e.g. "data.secret").
func DecryptionMiddleware(locations []string, decrypt DecryptFunc) gin.HandlerFunc {
	return func(c *gin.Context) {
		if len(locations) == 0 || decrypt == nil {
			c.Next()
			return
		}

		// Use a custom response writer to capture the body
		buf := &bytes.Buffer{}
		bw := &bodyWriter{ResponseWriter: c.Writer, buf: buf, statusCode: http.StatusOK}
		c.Writer = bw

		c.Next()

		body := buf.Bytes()
		if len(body) == 0 || bw.statusCode >= 400 {
			// Nothing to decrypt or error response; write as-is
			c.Writer = bw.ResponseWriter
			if len(body) > 0 {
				c.Writer.Write(body)
			}
			return
		}

		var data map[string]interface{}
		if err := json.Unmarshal(body, &data); err != nil {
			// Not JSON; write original
			c.Writer = bw.ResponseWriter
			c.Writer.Write(body)
			return
		}

		// Decrypt each location
		for _, loc := range locations {
			decryptNestedField(data, strings.Split(loc, "."), decrypt)
		}

		result, err := json.Marshal(data)
		if err != nil {
			c.Writer = bw.ResponseWriter
			c.Writer.Write(body)
			return
		}

		c.Writer = bw.ResponseWriter
		c.Writer.Header().Set("Content-Length", strconv.Itoa(len(result)))
		c.Writer.Write(result)
	}
}

// bodyWriter intercepts Write calls to capture the response body for gin.
type bodyWriter struct {
	gin.ResponseWriter
	buf        *bytes.Buffer
	statusCode int
}

func (bw *bodyWriter) WriteHeader(code int) {
	bw.statusCode = code
	// Do NOT forward WriteHeader; we write after decryption.
}

func (bw *bodyWriter) Write(b []byte) (int, error) {
	return bw.buf.Write(b)
}

func (bw *bodyWriter) WriteString(s string) (int, error) {
	return bw.buf.WriteString(s)
}

// decryptNestedField traverses the map following the key path and decrypts
// the leaf value in place.
func decryptNestedField(data map[string]interface{}, keys []string, decrypt DecryptFunc) {
	if len(keys) == 0 {
		return
	}

	current := data
	for i := 0; i < len(keys)-1; i++ {
		next, ok := current[keys[i]].(map[string]interface{})
		if !ok {
			return
		}
		current = next
	}

	lastKey := keys[len(keys)-1]
	val, ok := current[lastKey].(string)
	if !ok {
		return
	}

	decrypted, err := decrypt(val)
	if err != nil {
		slog.Error("DecryptionMiddleware: failed to decrypt field",
			"path", strings.Join(keys, "."),
			"error", err,
		)
		return
	}
	current[lastKey] = decrypted
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// CORS middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// CORSConfig controls the CORS middleware behaviour.
type CORSConfig struct {
	AllowOrigins []string // Defaults to ["*"]
	AllowMethods []string // Defaults to common methods
	AllowHeaders []string // Defaults to common headers
	MaxAge       int      // Access-Control-Max-Age in seconds
}

// CORS returns a gin middleware that sets CORS headers and handles preflight
// OPTIONS requests.
func CORS(cfg CORSConfig) gin.HandlerFunc {
	if len(cfg.AllowOrigins) == 0 {
		cfg.AllowOrigins = []string{"*"}
	}
	if len(cfg.AllowMethods) == 0 {
		cfg.AllowMethods = []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"}
	}
	if len(cfg.AllowHeaders) == 0 {
		cfg.AllowHeaders = []string{
			"Accept", "Authorization", "Content-Type", "X-Requested-With",
			"x-application-data", "x-user-data",
		}
	}
	if cfg.MaxAge == 0 {
		cfg.MaxAge = 86400
	}

	origins := strings.Join(cfg.AllowOrigins, ", ")
	methods := strings.Join(cfg.AllowMethods, ", ")
	headers := strings.Join(cfg.AllowHeaders, ", ")
	maxAge := strconv.Itoa(cfg.MaxAge)

	return func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", origins)
		c.Header("Access-Control-Allow-Methods", methods)
		c.Header("Access-Control-Allow-Headers", headers)
		c.Header("Access-Control-Max-Age", maxAge)

		if c.Request.Method == http.MethodOptions {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}

		c.Next()
	}
}

// ---------------------------------------------------------------------------
// RequestID middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// RequestID generates a unique request ID and stores it in the gin context
// and the X-Request-ID response header.
func RequestID() gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.GetHeader("X-Request-ID")
		if id == "" {
			id = generateRequestID()
			// Also set it on the REQUEST header so later middleware that reads
			// c.GetHeader("x-request-id") (e.g. OTelMiddleware's span attribute)
			// sees the minted id, not just the response header.
			c.Request.Header.Set("X-Request-ID", id)
		}
		c.Header("X-Request-ID", id)
		c.Set(ginKeyRequestID, id)
		ctx := context.WithValue(c.Request.Context(), ctxKeyRequestID, id)
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}

// generateRequestID creates a simple UUID v4-like identifier without external deps.
func generateRequestID() string {
	b := make([]byte, 16)
	_, _ = io.ReadFull(cryptoRandReader(), b)
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// cryptoRandReader returns crypto/rand.Reader. Separated for testability.
func cryptoRandReader() io.Reader {
	return cryptoRandReaderInstance
}

// ---------------------------------------------------------------------------
// MaxPayloadSize middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// MaxPayloadSize limits the request body to the given size string.
// Accepted formats: "2mb", "500kb", "1gb". Defaults to 2MB if parsing fails.
// This mirrors the MAX_REQUEST_PAYLOAD_SIZE env var.
func MaxPayloadSize(size string) gin.HandlerFunc {
	limit := parseSize(size)
	return func(c *gin.Context) {
		if c.Request.Body != nil {
			c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, limit)
		}
		c.Next()
	}
}

// GinMaxPayloadSize is an alias for MaxPayloadSize for use in server.go.
var GinMaxPayloadSize = MaxPayloadSize

// parseSize converts a human-readable size string to bytes.
func parseSize(s string) int64 {
	s = strings.TrimSpace(strings.ToLower(s))
	if s == "" {
		return 2 * 1024 * 1024
	}

	var multiplier int64 = 1
	numStr := s

	switch {
	case strings.HasSuffix(s, "gb"):
		multiplier = 1024 * 1024 * 1024
		numStr = strings.TrimSuffix(s, "gb")
	case strings.HasSuffix(s, "mb"):
		multiplier = 1024 * 1024
		numStr = strings.TrimSuffix(s, "mb")
	case strings.HasSuffix(s, "kb"):
		multiplier = 1024
		numStr = strings.TrimSuffix(s, "kb")
	case strings.HasSuffix(s, "b"):
		numStr = strings.TrimSuffix(s, "b")
	}

	n, err := strconv.ParseInt(strings.TrimSpace(numStr), 10, 64)
	if err != nil || n <= 0 {
		return 2 * 1024 * 1024
	}
	return n * multiplier
}

// ---------------------------------------------------------------------------
// ErrorHandlerWithLogger middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// ErrorHandlerWithLogger returns a gin middleware that catches panics and
// *FitError exceptions, returning structured JSON error responses.
func ErrorHandlerWithLogger(logger *slog.Logger) gin.HandlerFunc {
	if logger == nil {
		logger = slog.Default()
	}
	return func(c *gin.Context) {
		defer func() {
			if rv := recover(); rv != nil {
				logger.Error("panic recovered in ErrorHandler",
					"error", rv,
					"stack", string(debug.Stack()),
					"path", c.Request.URL.Path,
					"method", c.Request.Method,
				)

				switch e := rv.(type) {
				case *errors.FitError:
					status := e.HTTPStatusCode
					if status < 200 || status > 599 {
						status = http.StatusInternalServerError
					}
					c.AbortWithStatusJSON(status, map[string]interface{}{
						"error": map[string]interface{}{
							"code":    e.Code,
							"message": e.GetMessage(),
							"meta":    e.Meta,
						},
					})
				case error:
					c.AbortWithStatusJSON(http.StatusBadRequest, map[string]interface{}{
						"error": map[string]interface{}{
							"message": e.Error(),
						},
					})
				default:
					c.AbortWithStatusJSON(http.StatusInternalServerError, map[string]interface{}{
						"error": map[string]interface{}{
							"message": fmt.Sprintf("%v", rv),
						},
					})
				}
			}
		}()

		c.Next()
	}
}

// ---------------------------------------------------------------------------
// SecureHeaders middleware (gin.HandlerFunc)
// ---------------------------------------------------------------------------

// SecureHeaders returns a gin middleware that sets basic security headers equivalent
// to the helmet.js defaults used.
func SecureHeaders() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("X-Content-Type-Options", "nosniff")
		c.Header("X-DNS-Prefetch-Control", "off")
		c.Header("X-Download-Options", "noopen")
		c.Header("X-Frame-Options", "SAMEORIGIN")
		c.Header("X-XSS-Protection", "0")
		c.Header("Strict-Transport-Security", "max-age=15552000; includeSubDomains")
		c.Header("Referrer-Policy", "no-referrer")

		c.Next()
	}
}

// ---------------------------------------------------------------------------
// Legacy net/http compatible wrappers (for backward compatibility)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// envGet helper
// ---------------------------------------------------------------------------

var envGet = defaultEnvGet

func defaultEnvGet(key, fallback string) string {
	val := osGetenv(key)
	if val == "" {
		return fallback
	}
	return val
}
