// Copyright 2026 Fynd (Shopsense Retail Technologies Limited)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package errors provides Sentry error reporting integration for the fit.go framework.

package errors

import (
	"compress/gzip"
	"context"
	"encoding/json"
	"io"
	"maps"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"
	"time"

	sentrylib "github.com/getsentry/sentry-go"
	"github.com/gofynd/fit-go/redact"
)

func TestSentrySanitizerPreservesOpaqueTraceIDsAcrossPasses(t *testing.T) {
	trace := sentrylib.TraceID{}
	span := sentrylib.SpanID{}
	for i := range trace {
		trace[i] = 0x66
	}
	for i := range span {
		span[i] = 0x66
	}
	event := &sentrylib.Event{Contexts: map[string]sentrylib.Context{"trace": {
		"trace_id": trace, "span_id": span, "parent_span_id": span,
		"opaque_bytes": [16]byte(trace), "invalid_id": "alice@example.com",
		"password": trace,
	}}}
	for pass := 0; pass < 2; pass++ {
		event = sanitizeSentryEvent(event)
		values := event.Contexts["trace"]
		if values["trace_id"] != trace.String() || values["span_id"] != span.String() || values["parent_span_id"] != span.String() {
			t.Fatalf("pass %d corrupted trace identity: %v", pass, values)
		}
		if values["opaque_bytes"] != redact.Mask || values["password"] != redact.Mask || strings.Contains(values["invalid_id"].(string), "alice@example.com") {
			t.Fatal("trace identity exemption widened to sensitive values")
		}
	}
	for _, key := range []string{"trace_id", "span_id", "parent_span_id"} {
		if validSentryCorrelationID(key, "alice@example.com") || validSentryCorrelationID(key, strings.Repeat("g", 32)) {
			t.Fatalf("accepted invalid %s", key)
		}
	}
}

func TestSentryEnvelopePrivacyWithActualHTTPTransport(t *testing.T) {
	for _, synchronous := range []bool{true, false} {
		for _, fixture := range []struct {
			name    string
			private bool
			dsc     map[string]string
		}{
			{name: "checkout alice@example.com", private: true}, {name: "checkout"},
			{name: "checkout_private_key", private: true, dsc: map[string]string{
				"trace_id": strings.Repeat("6", 32), "9876543210": "safe",
			}},
			{name: "checkout_private_value", private: true, dsc: map[string]string{
				"trace_id": strings.Repeat("6", 32), "transaction": "alice@example.com",
			}},
		} {
			mode := "default_async/"
			if synchronous {
				mode = "sync/"
			}
			t.Run(mode+fixture.name, func(t *testing.T) {
				originalDSC := maps.Clone(fixture.dsc)
				captures := make(chan []byte, 1)
				receiver := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					var input io.Reader = r.Body
					if r.Header.Get("Content-Encoding") == "gzip" {
						reader, err := gzip.NewReader(r.Body)
						if err != nil {
							t.Error(err)
							return
						}
						defer reader.Close()
						input = reader
					}
					body, err := io.ReadAll(input)
					if err != nil {
						t.Error(err)
						return
					}
					captures <- body
					w.WriteHeader(http.StatusOK)
				}))
				defer receiver.Close()
				previous := sentrylib.CurrentHub().Client()
				defer sentrylib.CurrentHub().BindClient(previous)
				s := newTestSentry()
				var transport sentrylib.Transport
				if synchronous {
					transport = sentrylib.NewHTTPSyncTransport()
				}
				if err := s.InitWithConfig(SentryConfig{
					DSN:        strings.Replace(receiver.URL, "://", "://public@", 1) + "/1",
					SampleRate: 1, TracesSampleRate: 1, Transport: transport,
				}); err != nil {
					t.Fatal(err)
				}
				hub := sentrylib.NewHub(sentrylib.CurrentHub().Client(), sentrylib.NewScope())
				defer hub.Client().Close()
				if fixture.dsc != nil {
					// Scope.ApplyToEvent installs inbound DSC on error/message
					// events; transaction DSC is regenerated by that SDK stage.
					propagation := sentrylib.NewPropagationContext()
					propagation.DynamicSamplingContext = sentrylib.DynamicSamplingContext{Entries: fixture.dsc, Frozen: true}
					hub.Scope().SetPropagationContext(propagation)
					hub.CaptureMessage(fixture.name)
				} else {
					ctx := sentrylib.SetHubOnContext(context.Background(), hub)
					transaction := sentrylib.StartTransaction(ctx, fixture.name, sentrylib.WithTransactionSource(sentrylib.SourceCustom))
					transaction.Finish()
				}
				if !hub.Flush(time.Second) {
					t.Fatal("transport did not flush")
				}
				select {
				case body := <-captures:
					if strings.Contains(string(body), "alice@example.com") || strings.Contains(string(body), "9876543210") {
						t.Fatal("transaction PII leaked through envelope")
					}
					var envelope struct {
						Trace map[string]string `json:"trace"`
					}
					if err := json.Unmarshal([]byte(strings.SplitN(string(body), "\n", 2)[0]), &envelope); err != nil {
						t.Fatal(err)
					}
					if fixture.private && len(envelope.Trace) != 0 {
						t.Fatal("unsafe private sampling metadata retained")
					}
					if !fixture.private && envelope.Trace["transaction"] != "checkout" {
						t.Fatal("safe sampling metadata was dropped")
					}
					if !reflect.DeepEqual(fixture.dsc, originalDSC) {
						t.Fatal("shared SDK sampling map mutated")
					}
				case <-time.After(time.Second):
					t.Fatal("transaction was not exported")
				}
			})
		}
	}
}

func TestSentryPublicEventProjectionIncludesAllSDKFields(t *testing.T) {
	original := &sentrylib.Event{}
	fields := reflect.ValueOf(original).Elem()
	for i := 0; i < fields.NumField(); i++ {
		field := fields.Field(i)
		if !field.CanSet() {
			continue
		}
		seedSentryPublicField(field)
		if field.IsZero() {
			t.Fatalf("test must seed SDK field %s", fields.Type().Field(i).Name)
		}
	}
	cloned := reflect.ValueOf(sentryEventWithoutPrivateMetadata(original)).Elem()
	for i := 0; i < fields.NumField(); i++ {
		if fields.Type().Field(i).IsExported() && !reflect.DeepEqual(fields.Field(i).Interface(), cloned.Field(i).Interface()) {
			t.Fatalf("projection lost SDK public field %s", fields.Type().Field(i).Name)
		}
	}
}

func seedSentryPublicField(value reflect.Value) {
	if value.Type() == reflect.TypeOf(time.Time{}) {
		value.Set(reflect.ValueOf(time.Unix(1, 0)))
		return
	}
	switch value.Kind() {
	case reflect.String:
		value.SetString("fixture")
	case reflect.Ptr:
		value.Set(reflect.New(value.Type().Elem()))
	case reflect.Map:
		value.Set(reflect.MakeMap(value.Type()))
	case reflect.Slice:
		value.Set(reflect.MakeSlice(value.Type(), 1, 1))
	case reflect.Struct:
		for i := 0; i < value.NumField(); i++ {
			if value.Field(i).CanSet() {
				seedSentryPublicField(value.Field(i))
			}
		}
	}
}
