"""
Generate an authoritative cross-language encryption vector for fit-go G2.

This mirrors EXACTLY how pyfit (`pyfit.encryption`) and Node `fit/encryption`
encrypt PII: AES-256-GCM, fixed IV used verbatim (here a non-standard 9-byte
nonce, as production Vault secrets actually are), wire format
`base64(ciphertext) + "." + base64(tag)`.

It uses the same `cryptography` primitive (`modes.GCM`) that pyfit wraps, so the
emitted strings are a faithful reference for what the platform produces. The
output is pasted into fit-go/encryption/interop_kat_test.go as a known-answer
test so the Go test is self-contained (no Python needed in CI).
"""
import base64
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

# Deterministic, clearly-fake test material (NOT a real secret).
DEK = bytes(range(32))          # 32 bytes -> AES-256
IV  = bytes(range(9))           # 9 bytes  -> the real-world non-standard nonce length

PLAINTEXTS = [
    "swapnil@gofynd.com",       # email-like PII
    "+91-9876543210",           # phone-like PII
    "",                         # empty string edge case
    "héllo-uniçode-😀",    # multibyte / emoji
]

def encrypt(pt: str) -> str:
    enc = Cipher(algorithms.AES(DEK), modes.GCM(IV)).encryptor()
    ct = enc.update(pt.encode("utf-8")) + enc.finalize()
    tag = enc.tag                       # 16 bytes
    return base64.b64encode(ct).decode() + "." + base64.b64encode(tag).decode()

print("DEK_B64 =", base64.b64encode(DEK).decode())
print("IV_B64  =", base64.b64encode(IV).decode())
print("nonce_len =", len(IV))
print()
print("// --- Go known-answer vectors (generated by cryptography==%s, modes.GCM, 9-byte nonce) ---" %
      __import__("cryptography").__version__)
def go_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

for pt in PLAINTEXTS:
    print('\t{plaintext: %s, ciphertext: %s},' % (go_str(pt), go_str(encrypt(pt))))
